### ISSUE TITLE
运行一段时间后系统报错

### ISSUE THREAD

**Issue by 7estUser** [wuba/Antenna#123]
使用最新的docker镜像运行一段时间以后，dns解析失败并报错，报错内容：
匹配域名 xxxxxx 匹配结果: False
匹配域名 *.xxxxxxx 匹配结果: True
请求解析域名： a1.xxxxxxx
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/twisted/names/server.py", line 538, in messageReceived
    self.handleQuery(message, proto, address)
  File "/Antenna/modules/template/depend/listen/dnslog.py", line 43, in handleQuery
    return server.DNSServerFactory.handleQuery(self, message, protocol, address)
  File "/usr/lib/python3.10/site-packages/twisted/names/server.py", line 371, in handleQuery
    self.resolver.query(query)
  File "/usr/lib/python3.10/site-packages/twisted/names/common.py", line 78, in query
    return defer.maybeDeferred(method, query.name.name, timeout)
--- <exception caught here> ---
  File "/usr/lib/python3.10/site-packages/twisted/internet/defer.py", line 167, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python3.10/site-packages/twisted/names/common.py", line 84, in lookupAddress
    return self._lookup(dns.domainString(name), dns.IN, dns.A, timeout)
  File "/usr/lib/python3.10/site-packages/twisted/names/resolve.py", line 76, in _lookup
    d = self.resolvers[0].query(q, timeout)
  File "/Antenna/modules/template/depend/listen/dnslog.py", line 122, in query
    return defer.succeed(self._doDynamicResponse(query))
  File "/Antenna/modules/template/depend/listen/dnslog.py", line 95, in _doDynamicResponse
    if len(list(self.dns_recoed.get(domain=domain.lower()).value)) == 1:
  File "/usr/lib/python3.10/site-packages/django/db/models/query.py", line 431, in get
    num = len(clone)
  File "/usr/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 547, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 793, in _execute_command
    raise err.InterfaceError(0, "")
django.db.utils.InterfaceError: (0, '')

**Comment by bios000** [comment]
你目前使用的是最新版本的容器吗，我指的是latest版本

**Comment by 7estUser** [comment]
5月26日使用docker-compose -f compose.yml up -d安装的，拉取的应该是最新的吧？

**Comment by 7estUser** [comment]
compose.yml文件中国的services配置antenna: image: jihongjun/antenna:latest
是latest

**Comment by bios000** [comment]
了解了，将在2个工作日内修复

**Comment by bios000** [comment]
新版已经解决该问题
